# Generated by Django 3.2.21 on 2023-10-05 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='folder',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.folder'),
            preserve_default=False,
        ),
    ]
